---
- hosts: webservers
  tasks:
  - name: ensure git is at the latest version
    yum:
      name: git
      state: latest
  - name: ensure httpd is at the latest version
    yum:
      name: httpd
      state: latest
  - git:
      repo: 'https://github.com/mohanraz81/webtest'
      dest: /var/www/html
      version: master      
  - name: ensure apache is running
    service:
      name: httpd
      state: started
      enabled: yes
